"""Danh mục mã số Bảng cân đối kế toán — Mẫu B01-DN, Thông tư 200/2014/TT-BTC.

Nguồn: Thông tư 200/2014/TT-BTC, Phụ lục 2 (Mẫu B01-DN). Đây là danh mục dùng cho
doanh nghiệp niêm yết/quy mô lớn (không phải Thông tư 133 cho SME) — đổi từ quyết định
ban đầu ở design/roadmap.md Mục 13 ("Thông tư 133 trước") vì BCTC công khai HOSE/HNX
dùng để làm fixture test thực tế đều lập theo Thông tư 200. Ví dụ JSON ở design/api.md
Mục 9 (mã số 100/270) cũng khớp đúng Thông tư 200, không phải 133 — xem trao đổi ở
plans/. Thông tư 133 (B01a-DNN) có mã số khác hẳn, sẽ thêm sau dưới dạng bảng tra
riêng khi có fixture SME thật/tự soạn, dùng chung engine này.

Giới hạn v1 (ghi rõ, không âm thầm bỏ qua — design/pipeline.md Mục 8.2 điểm cuối):
bỏ qua các mã số có hậu tố chữ cái (411a/411b/421a/421b) và vài mục hiếm gặp
(323 Quỹ bình ổn giá, 339 Trái phiếu chuyển đổi, 340 Cổ phiếu ưu đãi) — không phải
lỗi, mà là phạm vi cố ý thu hẹp cho lần đầu.
"""

# Mã số -> tên chỉ tiêu chuẩn. Dùng làm danh mục fuzzy-match (design/pipeline.md Mục 8.2)
# và để rule engine tra cứu công thức tổng hợp.
MA_SO_200: dict[str, str] = {
    # --- TÀI SẢN NGẮN HẠN (100) ---
    "110": "Tiền và các khoản tương đương tiền",
    "111": "Tiền",
    "112": "Các khoản tương đương tiền",
    "120": "Đầu tư tài chính ngắn hạn",
    "121": "Chứng khoán kinh doanh",
    "122": "Dự phòng giảm giá chứng khoán kinh doanh",
    "123": "Đầu tư nắm giữ đến ngày đáo hạn",
    "130": "Các khoản phải thu ngắn hạn",
    "131": "Phải thu ngắn hạn của khách hàng",
    "132": "Trả trước cho người bán ngắn hạn",
    "133": "Phải thu nội bộ ngắn hạn",
    "134": "Phải thu theo tiến độ kế hoạch hợp đồng xây dựng",
    "135": "Phải thu về cho vay ngắn hạn",
    "136": "Phải thu ngắn hạn khác",
    "137": "Dự phòng phải thu ngắn hạn khó đòi",
    "139": "Tài sản thiếu chờ xử lý",
    "140": "Hàng tồn kho",
    "141": "Hàng tồn kho",
    "149": "Dự phòng giảm giá hàng tồn kho",
    "150": "Tài sản ngắn hạn khác",
    "151": "Chi phí trả trước ngắn hạn",
    "152": "Thuế giá trị gia tăng được khấu trừ",
    "153": "Thuế và các khoản khác phải thu Nhà nước",
    "155": "Tài sản ngắn hạn khác",
    "100": "Tài sản ngắn hạn",
    # --- TÀI SẢN DÀI HẠN (200) ---
    "210": "Các khoản phải thu dài hạn",
    "211": "Phải thu dài hạn của khách hàng",
    "212": "Trả trước cho người bán dài hạn",
    "213": "Vốn kinh doanh ở đơn vị trực thuộc",
    "214": "Phải thu nội bộ dài hạn",
    "215": "Phải thu về cho vay dài hạn",
    "216": "Phải thu dài hạn khác",
    "219": "Dự phòng phải thu dài hạn khó đòi",
    "220": "Tài sản cố định",
    "221": "Tài sản cố định hữu hình",
    "222": "Nguyên giá",
    "223": "Giá trị hao mòn lũy kế",
    "224": "Tài sản cố định thuê tài chính",
    "225": "Nguyên giá",
    "226": "Giá trị hao mòn lũy kế",
    "227": "Tài sản cố định vô hình",
    "228": "Nguyên giá",
    "229": "Giá trị hao mòn lũy kế",
    "230": "Bất động sản đầu tư",
    "231": "Nguyên giá",
    "232": "Giá trị hao mòn lũy kế",
    "240": "Tài sản dở dang dài hạn",
    "241": "Chi phí sản xuất, kinh doanh dở dang dài hạn",
    "242": "Chi phí xây dựng cơ bản dở dang",
    "250": "Đầu tư tài chính dài hạn",
    "251": "Đầu tư vào công ty con",
    "252": "Đầu tư vào công ty liên doanh, liên kết",
    "253": "Đầu tư góp vốn vào đơn vị khác",
    "254": "Dự phòng đầu tư tài chính dài hạn",
    "255": "Đầu tư nắm giữ đến ngày đáo hạn",
    "260": "Tài sản dài hạn khác",
    "261": "Chi phí trả trước dài hạn",
    "262": "Tài sản thuế thu nhập hoãn lại",
    "263": "Thiết bị, vật tư, phụ tùng thay thế dài hạn",
    "268": "Tài sản dài hạn khác",
    "200": "Tài sản dài hạn",
    "270": "Tổng cộng tài sản",
    # --- NỢ PHẢI TRẢ (300) ---
    "311": "Phải trả người bán ngắn hạn",
    "312": "Người mua trả tiền trước ngắn hạn",
    "313": "Thuế và các khoản phải nộp Nhà nước",
    "314": "Phải trả người lao động",
    "315": "Chi phí phải trả ngắn hạn",
    "316": "Phải trả nội bộ ngắn hạn",
    "317": "Phải trả theo tiến độ kế hoạch hợp đồng xây dựng",
    "318": "Doanh thu chưa thực hiện ngắn hạn",
    "319": "Phải trả ngắn hạn khác",
    "320": "Vay và nợ thuê tài chính ngắn hạn",
    "321": "Dự phòng phải trả ngắn hạn",
    "322": "Quỹ khen thưởng, phúc lợi",
    "324": "Giao dịch mua bán lại trái phiếu Chính phủ",
    "310": "Nợ ngắn hạn",
    "331": "Phải trả người bán dài hạn",
    "332": "Người mua trả tiền trước dài hạn",
    "333": "Chi phí phải trả dài hạn",
    "334": "Phải trả nội bộ về vốn kinh doanh",
    "335": "Phải trả nội bộ dài hạn",
    "336": "Doanh thu chưa thực hiện dài hạn",
    "337": "Phải trả dài hạn khác",
    "338": "Vay và nợ thuê tài chính dài hạn",
    "341": "Thuế thu nhập hoãn lại phải trả",
    "342": "Dự phòng phải trả dài hạn",
    "343": "Quỹ phát triển khoa học và công nghệ",
    "330": "Nợ dài hạn",
    "300": "Nợ phải trả",
    # --- VỐN CHỦ SỞ HỮU (400) ---
    "411": "Vốn góp của chủ sở hữu",
    "412": "Thặng dư vốn cổ phần",
    "413": "Quyền chọn chuyển đổi trái phiếu",
    "414": "Vốn khác của chủ sở hữu",
    "415": "Cổ phiếu quỹ",
    "416": "Chênh lệch đánh giá lại tài sản",
    "417": "Chênh lệch tỷ giá hối đoái",
    "418": "Quỹ đầu tư phát triển",
    "419": "Quỹ hỗ trợ sắp xếp doanh nghiệp",
    "420": "Quỹ khác thuộc vốn chủ sở hữu",
    "421": "Lợi nhuận sau thuế chưa phân phối",
    "422": "Nguồn vốn đầu tư xây dựng cơ bản",
    "410": "Vốn chủ sở hữu",
    "431": "Nguồn kinh phí",
    "432": "Nguồn kinh phí đã hình thành TSCĐ",
    "430": "Nguồn kinh phí và quỹ khác",
    "400": "Vốn chủ sở hữu",
    "440": "Tổng cộng nguồn vốn",
}

# Mã số là dòng TỔNG HỢP (subtotal/total) — nguồn cho rule engine dựng công thức
# cộng dồn tự động thay vì liệt kê tay từng công thức trong YAML (design/pipeline.md
# Mục 8.2: "nhầm chữ số là lỗi nghiêm trọng nhất" — công thức cộng dồn kiểm tra chéo
# chính là tuyến phòng thủ đầu tiên chống lỗi OCR đọc nhầm số).
SUBTOTAL_COMPONENTS: dict[str, list[str]] = {
    "100": ["110", "120", "130", "140", "150"],
    "200": ["210", "220", "230", "240", "250", "260"],
    "270": ["100", "200"],
    "310": [
        "311",
        "312",
        "313",
        "314",
        "315",
        "316",
        "317",
        "318",
        "319",
        "320",
        "321",
        "322",
        "324",
    ],
    "330": ["331", "332", "333", "334", "335", "336", "337", "338", "341", "342", "343"],
    "300": ["310", "330"],
    "410": [
        "411",
        "412",
        "413",
        "414",
        "415",
        "416",
        "417",
        "418",
        "419",
        "420",
        "421",
        "422",
    ],
    "430": ["431", "432"],
    "400": ["410", "430"],
    "440": ["300", "400"],
}
